import type { ModelMetadata } from './model.types.js';
import { emptyHealth } from './model.types.js';

function m(partial: Omit<ModelMetadata, 'health'>): ModelMetadata {
  return { ...partial, health: emptyHealth() };
}

export function seedModels(): ModelMetadata[] {
  return [
    m({
      id: 'nvidia/llama-3.1-nemotron-70b-instruct',
      providerName: 'nvidia',
      providerModelId: 'nvidia/llama-3.1-nemotron-70b-instruct',
      displayName: 'Llama 3.1 Nemotron 70B Instruct',
      contextWindow: 128_000,
      maxOutputTokens: 4096,
      capabilities: {
        streaming: true, toolCalling: true, vision: false,
        jsonMode: true, reasoning: true, anthropicCompat: false,
      },
      cost: { inputPerMTokUsd: 0, outputPerMTokUsd: 0 },
      tags: ['reasoning', 'code'],
      enabled: true,
      availability: 'AVAILABLE',
    }),
    m({
      id: 'nvidia/llama-3.3-nemotron-super-49b-v1',
      providerName: 'nvidia',
      providerModelId: 'nvidia/llama-3.3-nemotron-super-49b-v1',
      displayName: 'Llama 3.3 Nemotron Super 49B',
      contextWindow: 128_000,
      maxOutputTokens: 4096,
      capabilities: {
        streaming: true, toolCalling: true, vision: false,
        jsonMode: true, reasoning: true, anthropicCompat: false,
      },
      cost: { inputPerMTokUsd: 0, outputPerMTokUsd: 0 },
      tags: ['reasoning', 'fast'],
      enabled: true,
      availability: 'AVAILABLE',
    }),
    m({
      id: 'nvidia/qwen2.5-coder-32b-instruct',
      providerName: 'nvidia',
      providerModelId: 'qwen/qwen2.5-coder-32b-instruct',
      displayName: 'Qwen2.5 Coder 32B Instruct',
      contextWindow: 32_768,
      maxOutputTokens: 4096,
      capabilities: {
        streaming: true, toolCalling: true, vision: false,
        jsonMode: true, reasoning: false, anthropicCompat: false,
      },
      cost: { inputPerMTokUsd: 0, outputPerMTokUsd: 0 },
      tags: ['code', 'fast'],
      enabled: true,
      availability: 'AVAILABLE',
    }),
    m({
      id: 'nvidia/mistral-nemotron',
      providerName: 'nvidia',
      providerModelId: 'nvidia/mistral-nemotron',
      displayName: 'Mistral Nemotron',
      contextWindow: 128_000,
      maxOutputTokens: 4096,
      capabilities: {
        streaming: true, toolCalling: true, vision: false,
        jsonMode: true, reasoning: false, anthropicCompat: false,
      },
      cost: { inputPerMTokUsd: 0, outputPerMTokUsd: 0 },
      tags: ['chat', 'fast'],
      enabled: true,
      availability: 'AVAILABLE',
    }),
    m({
      id: 'nvidia/deepseek-r1',
      providerName: 'nvidia',
      providerModelId: 'deepseek-ai/deepseek-r1',
      displayName: 'DeepSeek R1',
      contextWindow: 128_000,
      maxOutputTokens: 8192,
      capabilities: {
        streaming: true, toolCalling: false, vision: false,
        jsonMode: false, reasoning: true, anthropicCompat: false,
      },
      cost: { inputPerMTokUsd: 0, outputPerMTokUsd: 0 },
      tags: ['reasoning', 'long-context'],
      enabled: true,
      availability: 'AVAILABLE',
    }),

    m({
      id: 'openrouter/anthropic/claude-3.5-sonnet',
      providerName: 'openrouter',
      providerModelId: 'anthropic/claude-3.5-sonnet',
      displayName: 'Claude 3.5 Sonnet (via OpenRouter)',
      contextWindow: 200_000,
      maxOutputTokens: 8192,
      capabilities: {
        streaming: true, toolCalling: true, vision: true,
        jsonMode: true, reasoning: true, anthropicCompat: true,
      },
      cost: { inputPerMTokUsd: 3, outputPerMTokUsd: 15 },
      tags: ['code', 'reasoning', 'anthropic-compat'],
      enabled: true,
      availability: 'AVAILABLE',
    }),
    m({
      id: 'openrouter/anthropic/claude-3.5-haiku',
      providerName: 'openrouter',
      providerModelId: 'anthropic/claude-3.5-haiku',
      displayName: 'Claude 3.5 Haiku (via OpenRouter)',
      contextWindow: 200_000,
      maxOutputTokens: 8192,
      capabilities: {
        streaming: true, toolCalling: true, vision: true,
        jsonMode: true, reasoning: false, anthropicCompat: true,
      },
      cost: { inputPerMTokUsd: 0.8, outputPerMTokUsd: 4 },
      tags: ['fast', 'cheap', 'anthropic-compat'],
      enabled: true,
      availability: 'AVAILABLE',
    }),
    m({
      id: 'openrouter/openai/gpt-4o-mini',
      providerName: 'openrouter',
      providerModelId: 'openai/gpt-4o-mini',
      displayName: 'GPT-4o mini',
      contextWindow: 128_000,
      maxOutputTokens: 16_384,
      capabilities: {
        streaming: true, toolCalling: true, vision: true,
        jsonMode: true, reasoning: false, anthropicCompat: false,
      },
      cost: { inputPerMTokUsd: 0.15, outputPerMTokUsd: 0.6 },
      tags: ['fast', 'cheap', 'chat'],
      enabled: true,
      availability: 'AVAILABLE',
    }),
    m({
      id: 'openrouter/qwen/qwen-2.5-coder-32b-instruct',
      providerName: 'openrouter',
      providerModelId: 'qwen/qwen-2.5-coder-32b-instruct',
      displayName: 'Qwen 2.5 Coder 32B',
      contextWindow: 32_768,
      maxOutputTokens: 4096,
      capabilities: {
        streaming: true, toolCalling: true, vision: false,
        jsonMode: true, reasoning: false, anthropicCompat: false,
      },
      cost: { inputPerMTokUsd: 0.07, outputPerMTokUsd: 0.16 },
      tags: ['code', 'cheap'],
      enabled: true,
      availability: 'AVAILABLE',
    }),
    m({
      id: 'openrouter/deepseek/deepseek-chat',
      providerName: 'openrouter',
      providerModelId: 'deepseek/deepseek-chat',
      displayName: 'DeepSeek V3 Chat',
      contextWindow: 64_000,
      maxOutputTokens: 8192,
      capabilities: {
        streaming: true, toolCalling: true, vision: false,
        jsonMode: true, reasoning: true, anthropicCompat: false,
      },
      cost: { inputPerMTokUsd: 0.14, outputPerMTokUsd: 0.28 },
      tags: ['reasoning', 'cheap', 'long-context'],
      enabled: true,
      availability: 'AVAILABLE',
    }),
  ];
}
